apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myservicedep
  name: myservicedep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myservicedep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myservicedep
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
