apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpdfrontend
  labels:
    app: guestbook
    tier: httpdfrontend
spec:
  # modify replicas according to your case
  replicas: 5
  selector:
    matchLabels:
      tier: httpdfrontend
  template:
    metadata:
      labels:
        tier: httpdfrontend
    spec:
      containers:
      - name: php-redis
        image: httpd
