apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: eee42e3c59abd60b508ec9f5286f3861aa42e76b61692430763ab0165ee4ca29
    cni.projectcalico.org/podIP: 10.190.104.19/32
    cni.projectcalico.org/podIPs: 10.190.104.19/32
  creationTimestamp: "2022-02-23T19:46:41Z"
  labels:
    run: httpd2
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:run: {}
      f:spec:
        f:containers:
          k:{"name":"httpd2"}:
            .: {}
            f:image: {}
            f:imagePullPolicy: {}
            f:name: {}
            f:resources: {}
            f:terminationMessagePath: {}
            f:terminationMessagePolicy: {}
        f:dnsPolicy: {}
        f:enableServiceLinks: {}
        f:restartPolicy: {}
        f:schedulerName: {}
        f:securityContext: {}
        f:terminationGracePeriodSeconds: {}
    manager: kubectl-run
    operation: Update
    time: "2022-02-23T19:46:41Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:cni.projectcalico.org/containerID: {}
          f:cni.projectcalico.org/podIP: {}
          f:cni.projectcalico.org/podIPs: {}
    manager: calico
    operation: Update
    time: "2022-02-23T19:46:43Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
          k:{"type":"ContainersReady"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Initialized"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
          k:{"type":"Ready"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:containerStatuses: {}
        f:hostIP: {}
        f:phase: {}
        f:podIP: {}
        f:podIPs:
          .: {}
          k:{"ip":"10.190.104.19"}:
            .: {}
            f:ip: {}
        f:startTime: {}
    manager: kubelet
    operation: Update
    time: "2022-02-23T19:47:05Z"
  name: httpd2
  namespace: default
  resourceVersion: "362650"
  uid: 67325ebe-c5e0-4517-88cd-f1820b6163cd
spec:
  containers:
  - image: httpd
    imagePullPolicy: Always
    name: httpd2
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-mgn5m
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: node2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-mgn5m
    secret:
      defaultMode: 420
      secretName: default-token-mgn5m
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T19:46:53Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T19:47:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T19:47:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-23T19:46:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5d11f4f193226a0cf996b807964ec05b9ae49f77bf51f33fa75b172613371560
    image: docker.io/httpd:latest
    imageID: docker-pullable://docker.io/httpd@sha256:5cc947a200524a822883dc6ce6456d852d7c5629ab177dfbf7e38c1b4a647705
    lastState: {}
    name: httpd2
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-02-23T19:47:16Z"
  hostIP: 192.168.31.97
  phase: Running
  podIP: 10.190.104.19
  podIPs:
  - ip: 10.190.104.19
  qosClass: BestEffort
  startTime: "2022-02-23T19:46:53Z"
